### ISSUE TITLE
Can't seem to browse to disk images on my Nokia 8 with Android 8.1

### ISSUE THREAD

**Issue by sandord** [squalldc/hataroid#3]
First off, thanks for building this great app!

Now, I can't seem to browse to disk images on my Nokia 8 with Android 8.1. I merely get the ".." option which then leads to "emulated" and "self" and another "..." which leads to a blank screen.

I can't find these locations when browsing the phone from the computer or otherwise make Hataroid browse to the root directory of my phone since I can't get beyond the blank screen.

**Comment by squalldc** [comment]
Hi,
- Are you using the latest v1.830. There was a possibly similar issue like that which was fixed in v1.801.
- Are you able to send me an android logcat output after browsing to the blank screen?

**Comment by sandord** [comment]
I'm on the latest version, yes.

But I'm not doing any Android development so I don't think I have the means of generating a logcat or whatever that is.

**Comment by sandord** [comment]
Here are some screen shots. I couldn't snap some of the steps before browsing started but that shouldn't matter as far as I can tell.

<img width="200" alt="1" src="https://user-images.githubusercontent.com/260737/45374612-eeeca780-b5f2-11e8-8f45-384a0447efd2.png">

<img width="200" alt="2" src="https://user-images.githubusercontent.com/260737/45374610-eeeca780-b5f2-11e8-9228-299c8e1cbd6a.png">

After tapping the "..":

<img width="200" alt="3" src="https://user-images.githubusercontent.com/260737/45374611-eeeca780-b5f2-11e8-8d5f-c316af53a0e5.png">

**Comment by squalldc** [comment]
I think this might be a permission issue.
I've updated the app to go back to the default storage folder reported by the android system when you browse to the root folder and it's not accessible.

**Comment by sandord** [comment]
Great, it works perfectly now. Thanks a lot!

**Comment by squalldc** [comment]
Good to hear :)
