### ISSUE TITLE
Bug: - Some keys cannot be mapped

### ISSUE THREAD

**Issue by TeamPandory** [squalldc/hataroid#5]
Keys W and A cannot be mapped.  When returning to the emulation, the entries are removed.

![image](https://user-images.githubusercontent.com/45140115/81517604-6fd6e600-9376-11ea-846e-5b0096c9c33e.png)

- enter emulation, only down and right work - return to input config screen

![image](https://user-images.githubusercontent.com/45140115/81517617-79604e00-9376-11ea-8690-efd0e160a73e.png)

**Comment by TeamPandory** [comment]
As left stick are keyboard inputs (W, A, S, D), it's impossible to change to an input for Hataroid right now.  Here's a video of your software in action on my box. - Very nice speeds ;-)
https://youtu.be/UmrlskdNN2w?t=112

**Comment by squalldc** [comment]
This was broken by a change in the last version.
I've put a test version with a fix in the releases section of this repository.
(Not sure if this will also fix the other #4 issue you mentioned earlier)

**Comment by TeamPandory** [comment]
Yeah - got a feeling it'd fix this but not the other issue-  will give it a try- thanks!

**Comment by TeamPandory** [comment]
Worked!  Thanks
