### ISSUE TITLE
Controller and other settings file

### ISSUE THREAD

**Issue by ctzio** [squalldc/hataroid#6]
Hello, 
This is more of a question than an issue. Is there a file where controller and other settings are saved? If so is it user editable and  can it be loaded from any directory?

>

**Comment by squalldc** [comment]
It's saved using Android's SharedPreferences system.
I don't think there's an easy way to manually modify it unless you have root.

There was a bug introduced in the last version where the input mapping was not getting saved correctly.
If you come across this issue, there's a test version in the releases page of this github repository.

**Comment by ctzio** [comment]
I see. I havent encountered the bug you mention. Since  I dont know anything about android, hatari supports execution with parameters from cli (or a bash script). Is that possible under hataroid?

**Comment by squalldc** [comment]
Hataroid can accept arguments by passing Android Intent Parameters when starting the activity (eg when starting Hataroid through another Android FrontEnd app).

The only argument currently supported is starting up with different discs inserted.

Is there something specific that you are wanting to do?

**Comment by ctzio** [comment]
Hello, sorry for not getting back sooner. I wanted to make a launch script for running games from a gemdos drive with specific options. For example run game as mega ste etc. I think from what you wrote this isnt possible. Thanks for you reply.
